import type { Metadata } from 'next'
import { Nunito_Sans, Source_Code_Pro } from 'next/font/google'
import './globals.css'

const nunito = Nunito_Sans({ subsets: ['latin'] })
const scode = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--scode',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  )
}
